var objShowName = 
{
	"EN":{
		"Wst": "Main weapon",
		"Clt": "Clothes",
		"Hed": "Head Gear",
		"Shs": "Shoes",
		"Wsb": "Sub weapon",
		"Wsp": "Special",
		"Charger": "Charger",
		"Keeper": "Keeper",
		"Light": "Light",
		"Long": "Long",
		"LongScope": "Long Scope",
		"Normal": "Normal",
		"NormalScope": "Normal Scope",
		"Quick": "Quick",
		"Roller": "Roller",
		"BrushMini": "Brush Mini",
		"BrushNormal": "Brush Normal",
		"Compact": "Compact",
		"Heavy": "Heavy",
		"Hunter": "Hunter",
		"Shooter": "Shooter",
		"BlasterLight": "Blaster Light",
		"BlasterLightLong": "Blaster Light Long",
		"BlasterLightShort": "Blaster Light Short",
		"BlasterLong": "Blaster Long",
		"BlasterMiddle": "Blaster Middle",
		"BlasterShort": "Blaster Short",
		"Blaze": "Blaze",
		"Expert": "Expert",
		"First": "First",
		"Flash": "Flash",
		"Gravity": "Gravity",
		"Precision": "Precision",
		"QuickMiddle": "Quick Middle",
		"Short": "Short",
		"TripleMiddle": "Triple Middle",
		"TripleQuick": "Triple Quick",
		"Slosher": "Slosher",
		"Diffusion": "Diffusion",
		"Launcher": "Launcher",
		"Strong": "Strong",
		"Spinner": "Spinner",
		"Twins": "Twins",
		"Dual": "Dual",
		"Gallon": "Gallon",
		"Stepper": "Stepper",
		"Umbrella": "Umbrella",
		"Bomb": "Bomb",
		"AMB": "Amiibo",
		"CAP": "Cap",
		"COP": "Salmon Run",
		"EYE": "Glasses",
		"FST": "First",
		"HAT": "Hat",
		"HBD": "Headband",
		"HDP": "Headset",
		"MET": "Helmet",
		"MSK": "Mask",
		"MSN": "Hero Mode",
		"NCP": "Beanie",
		"VIS": "Visor",
		"HAP": "Splat fest ",
		"JKT": "Jacket",
		"PLO": "Polo",
		"PRK": "Hoodie",
		"SHT": "Casual",
		"SWT": "Sweater",
		"TEL": "Long-sleeve",
		"TES": "Tee",
		"TLY": "Layered-look",
		"TNK": "TankTop",
		"VST": "Vest",
		"BOT": "Boots",
		"CFS": "Casuals",
		"LTS": "Leather ",
		"SDL": "Slippers ",
		"SHI": "Hi-Tops",
		"SLO": "Low-Tops",
		"SLP": "SkateShoes",
		"TRS": "TrailBoots",
		"Hyper": "Hyper",
		"Standard": "Standard",
		"Curling": "Curling",
		"Robo": "AutoBomb",
		"Splash": "Splat -Bomb",
		"Suction": "Suction",
		"Flag": "SquidBeakon",
		"PointSensor": "PointSensor",
		"PoisonFog": "ToxicMist",
		"Shield": "SplashWall",
		"Sprinkler": "Sprinkler",
		"TimerTrap": "InkMine",
		"AquaBall": "Baller",
		"Jetpack": "Inkjet",
		"LauncherCurling": "Curling-BombLauncher",
		"LauncherQuick": "Burst-BombLauncher",
		"LauncherRobo": "AutobombLauncher",
		"LauncherSplash": "Splat-BombLauncher",
		"LauncherSuction": "Suction-BombLauncher",
		"RainCloud": "InkStorm",
		"SuperArmor": "InkArmor",
		"SuperBubble": "BubbleBlower",
		"SuperLanding": "Splashdown",
		"SuperMissile": "TentaMissiles",
		"WaterCutter": "StingRay"
	},
	"TW":
	{
		"Wst": "主武器",
		"Clt": "衣服",
		"Hed": "頭飾",
		"Shs": "鞋子",
		"Wsb": "副武器",
		"Wsp": "特殊",
		"Charger": "蓄力",
		"Keeper": "水管(守護者)",
		"Light": "輕型",
		"Long": "長型",
		"LongScope": "長型配狙擊鏡",
		"Normal": "一般",
		"NormalScope": "一般配狙擊鏡",
		"Quick": "快速",
		"Roller": "滾筒",
		"BrushMini": "畫筆(迷你刷)",
		"BrushNormal": "油漆刷(一般刷)",
		"Compact": "碳纖",
		"Heavy": "重型",
		"Hunter": "鋼筆(獵人)",
		"Shooter": "射手",
		"BlasterLight": "爆裂輕型",
		"BlasterLightLong": "爆裂輕型長型",
		"BlasterLightShort": "蠟筆(爆裂輕型短型)",
		"BlasterLong": "爆裂長程",
		"BlasterMiddle": "爆裂中程",
		"BlasterShort": "猥褻槍(爆裂短型)",
		"Blaze": "噴漆(火焰)",
		"Expert": "有錢人的水槍",
		"First": "窮人的水槍(第一把、方塊槍)",
		"Flash": "香檳槍",
		"Gravity": "加農",
		"Precision": "針槍",
		"QuickMiddle": "光槍",
		"Short": "短型",
		"TripleMiddle": "三連發中型",
		"TripleQuick": "三連發快速",
		"Slosher": "水桶",
		"Diffusion": "洗筆筒",
		"Launcher": "洗機機(對我故意的)",
		"Strong": "避震器",
		"Spinner": "格林",
		"Twins": "雙槍",
		"Dual": "高壓水槍",
		"Gallon": "熱熔槍",
		"Stepper": "Stepper",
		"Umbrella": "雨傘",
		"Bomb": "炸彈",
		"AMB": "Amiibo",
		"CAP": "球帽",
		"COP": "鮭魚快跑",
		"EYE": "眼鏡",
		"FST": "菜逼八",
		"HAT": "漁夫帽",
		"HBD": "頭帶",
		"HDP": "耳機",
		"MET": "安全帽",
		"MSK": "口罩",
		"MSN": "英雄模式",
		"NCP": "毛帽",
		"VIS": "遮陽帽",
		"HAP": "祭典",
		"JKT": "夾克",
		"PLO": "Polo",
		"PRK": "帽T",
		"SHT": "休閒",
		"SWT": "毛衣",
		"TEL": "長T",
		"TES": "T恤",
		"TLY": "兩件式",
		"TNK": "吊嘎",
		"VST": "無袖背心",
		"BOT": "靴",
		"CFS": "休閒",
		"LTS": "皮鞋",
		"SDL": "拖鞋",
		"SHI": "高筒",
		"SLO": "短筒",
		"SLP": "時尚時尚最時尚",
		"TRS": "登山鞋",
		"Hyper": "Hyper",
		"Standard": "標準",
		"Curling": "冰壺",
		"Robo": "青蛙",
		"Splash": "粽子",
		"Suction": "吸盤",
		"Flag": "雷達",
		"PointSensor": "點感測器",
		"PoisonFog": "毒霧",
		"Shield": "牆",
		"Sprinkler": "灑水器",
		"TimerTrap": "地雷",
		"AquaBall": "倉鼠球",
		"Jetpack": "噴射背包",
		"LauncherCurling": "冰壺發射器",
		"LauncherQuick": "水球發射器",
		"LauncherRobo": "青蛙發射器",
		"LauncherSplash": "好飽",
		"LauncherSuction": "吸盤發射器",
		"RainCloud": "墨水風暴",
		"SuperArmor": "墨水裝甲",
		"SuperBubble": "泡泡",
		"SuperLanding": "捶地",
		"SuperMissile": "飛彈",
		"WaterCutter": "不是我尿的"
	}
};